### ISSUE TITLE
add cancel links to all forms

### ISSUE THREAD

**Issue by edraut** [edraut/pulitzer#6]
There should be an option to 'cancel' in each form.
for new post types, content_element types, content_elements, etc., it should close the new form
for editing existing post type details, it should get the basic view of the post type with all the control links (manage, template, details) and just replace the form
for editing content elements, the cancel link should just get the show(read-only) view of the element and replace the form with it.

**Comment by gomayonqui** [comment]
Released in version 0.2.0
